### ISSUE TITLE
Outdated Dropbox PHP SDK used

### ISSUE THREAD

**Issue by afterlogic** [sash04ek/afterlogic-dropbox-plugin#1]
Hello,

One of our clients has reported that there's an issue with the plugin code, specifically libs/Dropbox/Curl.php on line 69 it enforces SSLv3 which for the most part is completely disabled due to the POODLE vulnerability: 

$this->set(CURLOPT_SSLVERSION, 3);          // Enforce SSL v3.

Seems like Dropbox team has already updated their SDK and the value set in current version is 1. We'd appreciate if you update that in your plugin as well.
## 

Regards,
Igor, AfterLogic Support

**Comment by sash04ek** [comment]
Thank you! Fixed
